name: Run linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2']
        os: [ubuntu-latest]
        experimental: [false]

    name: Run rubocop with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install addons
        run: sudo apt-get install libgmp3-dev libcap-ng-dev
      - name: Install dependencies
        run: bundle install
      - name: Install rubocop and rubocop-performance
        run: gem install rubocop rubocop-performance
      - name: Run rubocop
        run: rubocop
